export const teamMembers = [
    {
        name: "Arianne L. Palmer",
        role: "Attorney",
        image: "/images/female_placeholder_1.jpg",
        email: "arianne.palmer@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "John D. Smith",
        role: "Paralegal",
        image: "/images/male_placeholder_1.jpg",
        email: "john.smith@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Emily R. Johnson",
        role: "Legal Assistant",
        image: "/images/female_placeholder_2.jpg",
        email: "emily.johnson@hotmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Michael B. Lee",
        role: "Office Manager",
        image: "/images/male_placeholder_2.jpg",
        email: "michael.lee@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Sophia K. Martinez",
        role: "Receptionist",
        image: "/images/female_placeholder_3.jpg",
        email: "sophia.martinez@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "David A. Brown",
        role: "Intern",
        image: "/images/male_placeholder_3.jpg",
        email: "david.brown@hotmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Olivia M. Davis",
        role: "Attorney",
        image: "/images/female_placeholder_4.jpg",
        email: "olivia.davis@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "James C. Wilson",
        role: "Paralegal",
        image: "/images/male_placeholder_4.jpg",
        email: "james.wilson@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Isabella N. Moore",
        role: "Legal Assistant",
        image: "/images/female_placeholder_5.jpg",
        email: "isabella.moore@hotmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "William D. Taylor",
        role: "Office Manager",
        image: "/images/male_placeholder_5.jpg",
        email: "william.taylor@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Mia P. Anderson",
        role: "Receptionist",
        image: "/images/female_placeholder_6.jpg",
        email: "mia.anderson@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Alexander J. Thomas",
        role: "Intern",
        image: "/images/male_placeholder_6.jpg",
        email: "alexander.thomas@hotmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Charlotte R. Jackson",
        role: "Attorney",
        image: "/images/female_placeholder_7.jpg",
        email: "charlotte.jackson@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Benjamin K. White",
        role: "Paralegal",
        image: "/images/male_placeholder_7.jpg",
        email: "benjamin.white@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Amelia S. Harris",
        role: "Legal Assistant",
        image: "/images/female_placeholder_8.jpg",
        email: "amelia.harris@hotmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Daniel L. Martin",
        role: "Office Manager",
        image: "/images/male_placeholder_8.jpg",
        email: "daniel.martin@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Evelyn T. Thompson",
        role: "Receptionist",
        image: "/images/female_placeholder_9.jpg",
        email: "evelyn.thompson@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Matthew R. Garcia",
        role: "Intern",
        image: "/images/male_placeholder_9.jpg",
        email: "matthew.garcia@hotmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Abigail W. Martinez",
        role: "Attorney",
        image: "/images/female_placeholder_10.jpg",
        email: "abigail.martinez@gmail.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
    {
        name: "Christopher N. Robinson",
        role: "Paralegal",
        image: "/images/male_placeholder_10.jpg",
        email: "christopher.robinson@yahoo.com",
        socials: [
            { icon: "F", url: "https://www.facebook.com" },
            { icon: "T", url: "https://www.twitter.com" },
            { icon: "I", url: "https://www.instagram.com" },
        ],
    },
];

